"""Persist pipeline results as documents under $HOME/research/<topic-slug>/.

Writes four files per run:
    notes.md      raw research notes (markdown)
    summary.json  the structured summary object
    summary.md    human-readable summary with YAML frontmatter (Obsidian-ready)
    result.json   the full run_pipeline() result

Destination base is RESEARCH_DIR if set, else ~/research.

If OBSIDIAN_VAULT is set, also symlinks summary.md into <vault>/Research/<slug>.md
and drops an unhook.sh into the result dir that removes that symlink.
"""

import datetime
import json
import os
import re


def slugify(topic, maxlen=80):
    """Filesystem-safe directory name from a topic string."""
    s = re.sub(r"[^a-z0-9]+", "-", topic.lower()).strip("-")
    return s[:maxlen].strip("-") or "untitled"


def summary_md(result):
    s = result["summary"]
    key_points = "\n".join(f"- {p}" for p in s.get("keyPoints", []))
    frontmatter = (
        "---\n"
        f'topic: "{result["topic"]}"\n'
        f"date: {datetime.date.today().isoformat()}\n"
        f'verdict: {result.get("verdict", "")}\n'
        "tags: [research, multi-agent-101]\n"
        "---\n\n"
    )
    return (
        frontmatter
        + f"# {s.get('title', '(untitled)')}\n\n"
        f"**Topic:** {result['topic']}\n\n"
        f"## Key Points\n\n{key_points}\n\n"
        f"## Takeaway\n\n{s.get('takeaway', '')}\n\n"
        f"## Research Notes\n\n{result['notes']}\n"
    )


def _write_unhook_script(out_dir, link):
    path = os.path.join(out_dir, "unhook.sh")
    script = (
        "#!/usr/bin/env bash\n"
        "# Auto-generated by the multi-agents pipeline.\n"
        "# Removes the Obsidian symlink created for this topic.\n"
        "# Safe: only removes the path if it is a symlink.\n"
        f'link="{link}"\n'
        'if [ -L "$link" ]; then\n'
        '  rm "$link" && echo "unhooked: $link"\n'
        "else\n"
        '  echo "no symlink at: $link"\n'
        "fi\n"
    )
    with open(path, "w") as f:
        f.write(script)
    os.chmod(path, 0o755)
    return path


def _ensure_vault(vault):
    """Make `vault` a standalone Obsidian vault by creating a minimal .obsidian/
    marker if one isn't already there. Existing config is left untouched."""
    dot_obsidian = os.path.join(vault, ".obsidian")
    app_json = os.path.join(dot_obsidian, "app.json")
    if not os.path.isdir(dot_obsidian):
        os.makedirs(dot_obsidian, exist_ok=True)
    if not os.path.exists(app_json):
        with open(app_json, "w") as f:
            f.write("{}\n")


def hook_obsidian(result, out_dir):
    """Symlink summary.md into the Obsidian vault; return the link path or None.

    Auto-provisions the vault (creates it + a minimal .obsidian/ marker) so a
    per-project OBSIDIAN_VAULT works with no manual "open as vault" step.
    No-op (returns None) when OBSIDIAN_VAULT is unset, or when a real
    (non-symlink) file already occupies the target — we never clobber notes.
    """
    vault = os.environ.get("OBSIDIAN_VAULT")
    if not vault:
        return None

    _ensure_vault(vault)
    research_sub = os.path.join(vault, "Research")
    os.makedirs(research_sub, exist_ok=True)
    link = os.path.join(research_sub, f"{slugify(result['topic'])}.md")
    src = os.path.abspath(os.path.join(out_dir, "summary.md"))

    if os.path.islink(link):
        os.remove(link)  # refresh our own prior link
    elif os.path.lexists(link):
        return None  # a real file is there; leave it alone

    os.symlink(src, link)
    _write_unhook_script(out_dir, link)
    return link


def write_outputs(result, base_dir=None):
    """Write the four documents (and Obsidian hook); return the topic directory."""
    base = base_dir or os.environ.get("RESEARCH_DIR") or os.path.expanduser("~/research")
    out_dir = os.path.join(base, slugify(result["topic"]))
    os.makedirs(out_dir, exist_ok=True)

    with open(os.path.join(out_dir, "notes.md"), "w") as f:
        f.write(f"# {result['topic']}\n\n{result['notes']}\n")
    with open(os.path.join(out_dir, "summary.json"), "w") as f:
        json.dump(result["summary"], f, indent=2)
    with open(os.path.join(out_dir, "summary.md"), "w") as f:
        f.write(summary_md(result))
    with open(os.path.join(out_dir, "result.json"), "w") as f:
        json.dump(result, f, indent=2)

    hook_obsidian(result, out_dir)
    return out_dir
