"""Persist pipeline results as documents under $HOME/research/<topic-slug>/.

Writes four files per run:
    notes.md      raw research notes (markdown)
    summary.json  the structured summary object
    summary.md    human-readable summary with YAML frontmatter (Obsidian-ready)
    result.json   the full run_pipeline() result

Destination base is RESEARCH_DIR if set, else ~/research.

If OBSIDIAN_VAULT is set, also symlinks summary.md into <vault>/Research/<slug>.md
and drops an unhook.sh into the result dir that removes that symlink.
"""

import json
import os
import re
import secrets
import time


def slugify(topic, maxlen=80):
    """Filesystem-safe directory name from a topic string."""
    s = re.sub(r"[^a-z0-9]+", "-", topic.lower()).strip("-")
    return s[:maxlen].strip("-") or "untitled"


def research_base():
    return os.environ.get("RESEARCH_DIR") or os.path.expanduser("~/research")


def _write_unhook_script(out_dir, link):
    path = os.path.join(out_dir, "unhook.sh")
    script = (
        "#!/usr/bin/env bash\n"
        "# Auto-generated by the multi-agents pipeline.\n"
        "# Removes the Obsidian symlink created for this topic.\n"
        "# Safe: only removes the path if it is a symlink.\n"
        f'link="{link}"\n'
        'if [ -L "$link" ]; then\n'
        '  rm "$link" && echo "unhooked: $link"\n'
        "else\n"
        '  echo "no symlink at: $link"\n'
        "fi\n"
    )
    with open(path, "w") as f:
        f.write(script)
    os.chmod(path, 0o755)
    return path


def _ensure_vault(vault):
    """Make `vault` a standalone Obsidian vault by creating a minimal .obsidian/
    marker if one isn't already there. Existing config is left untouched."""
    dot_obsidian = os.path.join(vault, ".obsidian")
    app_json = os.path.join(dot_obsidian, "app.json")
    if not os.path.isdir(dot_obsidian):
        os.makedirs(dot_obsidian, exist_ok=True)
    if not os.path.exists(app_json):
        with open(app_json, "w") as f:
            f.write("{}\n")


def _obsidian_config_candidates():
    """Possible locations of Obsidian's vault registry (obsidian.json), most
    common first. Home-relative so it works for any user. OBSIDIAN_CONFIG
    overrides for non-standard installs."""
    override = os.environ.get("OBSIDIAN_CONFIG")
    if override:
        return [override]
    home = os.path.expanduser("~")
    return [
        os.path.join(home, ".config/obsidian/obsidian.json"),  # native Linux
        os.path.join(home, ".var/app/md.obsidian.Obsidian/config/obsidian/obsidian.json"),  # flatpak
        os.path.join(home, "snap/obsidian/current/.config/obsidian/obsidian.json"),  # snap
        os.path.join(home, "Library/Application Support/obsidian/obsidian.json"),  # macOS
        os.path.join(os.environ.get("APPDATA", ""), "obsidian/obsidian.json"),  # Windows
    ]


def _find_obsidian_config():
    for path in _obsidian_config_candidates():
        if path and os.path.isfile(path):
            return path
    return None


def register_vault(vault_path):
    """Add the vault to Obsidian's registry so it appears in the app's switcher.

    Idempotent (no duplicate if the path is already registered). Best-effort:
    returns False and changes nothing if Obsidian's config can't be found or
    read. Takes effect on Obsidian's next launch; if Obsidian is running it may
    overwrite the file on exit, so a restart may be needed.
    """
    cfg = _find_obsidian_config()
    if not cfg:
        return False
    vault_path = os.path.abspath(vault_path)
    try:
        with open(cfg) as f:
            data = json.load(f)
    except (OSError, json.JSONDecodeError):
        return False

    vaults = data.setdefault("vaults", {})
    if any(v.get("path") == vault_path for v in vaults.values()):
        return True  # already registered
    vaults[secrets.token_hex(8)] = {
        "path": vault_path,
        "ts": int(time.time() * 1000),
        "open": False,
    }
    try:
        with open(cfg, "w") as f:
            json.dump(data, f, indent=2)
    except OSError:
        return False
    return True


def hook_obsidian_dir(out_dir, name):
    """Symlink the whole research folder into the Obsidian vault; return the link
    path or None.

    The folder (not a single file) is linked so every note in it — index,
    sources, summary — lands in the vault and their [[wikilinks]] resolve there,
    which is what lets Obsidian build the graph across them.

    Auto-provisions the vault. No-op (returns None) when OBSIDIAN_VAULT is unset,
    or when a real (non-symlink) path already occupies the target — we never
    clobber existing notes.
    """
    vault = os.environ.get("OBSIDIAN_VAULT")
    if not vault:
        return None

    _ensure_vault(vault)
    register_vault(vault)  # best-effort: make it show in Obsidian's switcher
    research_sub = os.path.join(vault, "Research")
    os.makedirs(research_sub, exist_ok=True)
    link = os.path.join(research_sub, name)
    src = os.path.abspath(out_dir)

    if os.path.islink(link):
        os.remove(link)  # refresh our own prior link
    elif os.path.lexists(link):
        return None  # a real path is there; leave it alone

    os.symlink(src, link, target_is_directory=True)
    _write_unhook_script(out_dir, link)
    return link
